name: Building on Linux
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup required packages
        run: sudo apt-get install -y binutils-dev libssl-dev uuid-dev

      - name: Setup GCC
        uses: egor-tensin/setup-gcc@v1

      - name: Create build directory
        run: mkdir build

      - name: Cmake build
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: Cmake make
        run: cmake --build build --config Release --target main -j4

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: main_linux
          path: build/bin/main*