name: Building on Windows
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Visual Studio"
        uses: egor-tensin/vs-shell@v2

      - name: Create build directory
        run: mkdir build

      - name: Cmake build
        run: cmake -S. -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: Cmake make
        run: cmake --build build --config Release --target main -j4

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: main_windows
          path: build/bin/main*